#!/bin/bash
set -e

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS appliance_product_db;
  CREATE DATABASE IF NOT EXISTS appliance_cart_db;
  CREATE DATABASE IF NOT EXISTS appliance_sales_db;
  CREATE DATABASE IF NOT EXISTS appliance_notification_db;

  CREATE USER IF NOT EXISTS '${APPLIANCE_DB_USERNAME}'@'%' IDENTIFIED BY '${APPLIANCE_DB_PASSWORD}';

  GRANT ALL PRIVILEGES ON appliance_product_db.* TO '${APPLIANCE_DB_USERNAME}'@'%';
  GRANT ALL PRIVILEGES ON appliance_cart_db.* TO '${APPLIANCE_DB_USERNAME}'@'%';
  GRANT ALL PRIVILEGES ON appliance_sales_db.* TO '${APPLIANCE_DB_USERNAME}'@'%';
  GRANT ALL PRIVILEGES ON appliance_notification_db.* TO '${APPLIANCE_DB_USERNAME}'@'%';

  CREATE USER IF NOT EXISTS '${DEBEZIUM_DB_USER}'@'%' IDENTIFIED BY '${DEBEZIUM_DB_PASSWORD}';

  GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${DEBEZIUM_DB_USER}'@'%';

  FLUSH PRIVILEGES;
EOSQL