spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: "${CONFIG_REPOSITORY_URL:https://github.com/JLeonelMartins/appliance-store-config.git}"
          default-label: main
          clone-on-start: true

          # Evita consultar GitHub en cada petición.
          refresh-rate: 30

          # Tiempo máximo para conectarse al repositorio Git, en segundos.
          timeout: 15

server:
  port: ${SERVER_PORT:8888}