spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/JLeonelMartins/appliance-store-config.git}
          default-label: ${CONFIG_REPO_BRANCH:main}
          clone-on-start: true

          # Avoid checking GitHub on every request.
          refresh-rate: 30

          # Maximum time to connect to the Git repository, in seconds.
          timeout: 15

server:
  port: ${SERVER_PORT:8888}